# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "FOUTOURE Store"
client_id = "4a5a7249e2011fedf6cabc80b67c3298"
application_url = "https://foutoure-store.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_metaobjects,read_metaobjects,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://foutoure-store.vercel.app/auth/callback",
  "https://foutoure-store.vercel.app/api/auth/callback/shopify"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
include_config_on_deploy = true

# Metafield Definitions
[[metafields]]
namespace = "announcements"
key = "announcement_enabled"
type = "boolean"
name = "Enable Announcement Bar"
description = "Toggle the announcement bar visibility"
owner_resource = "shop"
owner_type = "shop"
visible_to_storefront_api = true
access_type = "public_read_write"
pinned = true

[[metafields]]
namespace = "announcements"
key = "announcement_text"
type = "single_line_text_field"
name = "Announcement Text"
description = "The main text to display in the announcement bar"
owner_resource = "shop"
owner_type = "shop"
visible_to_storefront_api = true
access_type = "public_read_write"
pinned = true

[[metafields]]
namespace = "announcements"
key = "announcement_end_date"
type = "date_time"
name = "End Date"
description = "When the announcement should expire"
owner_resource = "shop"
owner_type = "shop"
visible_to_storefront_api = true
access_type = "public_read_write"
pinned = true

[[metafields]]
namespace = "announcements"
key = "announcement_promo_code"
type = "single_line_text_field"
name = "Promo Code"
description = "Promotion code to display"
owner_resource = "shop"
owner_type = "shop"
visible_to_storefront_api = true
access_type = "public_read_write"
pinned = true

[[metafields]]
namespace = "announcements"
key = "announcement_gradient_from"
type = "single_line_text_field"
name = "Gradient Start Color"
description = "Starting color of the gradient (Tailwind color class)"
owner_resource = "shop"
owner_type = "shop"
visible_to_storefront_api = true
access_type = "public_read_write"
pinned = true

[[metafields]]
namespace = "announcements"
key = "announcement_gradient_to"
type = "single_line_text_field"
name = "Gradient End Color"
description = "Ending color of the gradient (Tailwind color class)"
owner_resource = "shop"
owner_type = "shop"
visible_to_storefront_api = true
access_type = "public_read_write"
pinned = true

[[metafields]]
namespace = "social_media"
key = "instagram_url"
type = "single_line_text_field"
name = "Instagram URL"
description = "Your store's Instagram profile URL"

[[metafields]]
namespace = "social_media"
key = "facebook_url"
type = "single_line_text_field"
name = "Facebook URL"
description = "Your store's Facebook page URL"

[[metafields]]
namespace = "store_info"
key = "contact_email"
type = "email"
name = "Contact Email"
description = "Primary contact email for customers"

[[metafields]]
namespace = "store_info"
key = "phone_number"
type = "single_line_text_field"
name = "Phone Number"
description = "Store contact phone number"

[[metafields]]
namespace = "seo"
key = "default_meta_description"
type = "multi_line_text_field"
name = "Default Meta Description"
description = "Default meta description for pages without specific SEO settings"

[[metafields]]
namespace = "footer"
key = "about_text"
type = "multi_line_text_field"
name = "About Us Text"
description = "Short description about your store for the footer"

[[metafields]]
namespace = "shipping"
key = "free_shipping_threshold"
type = "number_decimal"
name = "Free Shipping Threshold"
description = "Order amount required for free shipping"

[[metafields]]
namespace = "customer_service"
key = "return_policy"
type = "multi_line_text_field"
name = "Return Policy"
description = "Store return policy details"

[[metafields]]
namespace = "homepage"
key = "featured_collection"
type = "single_line_text_field"
name = "Featured Collection Handle"
description = "Handle of the collection to feature on homepage"

[[metafields]]
namespace = "homepage"
key = "hero_heading"
type = "single_line_text_field"
name = "Hero Section Heading"
description = "Main heading for the homepage hero section"

[[metafields]]
namespace = "homepage"
key = "hero_subtext"
type = "multi_line_text_field"
name = "Hero Section Subtext"
description = "Supporting text for the homepage hero section"
